### PR TITLE
Update website for MADlib 1.21 release.

### PR DESCRIPTION
**Pull request by edespino**
@fmcquillan99 & @rahiyer - Here are my proposed 1.21 site and doc updates.  Please review at your earliest convenience.

-=e

### CODE REVIEW

**Comment by fmcquillan99** [comment]
Ed, is update of the 
http://madlib.apache.org/download.html
included in this PR?

**Comment by fmcquillan99** [comment]
Also note in the past we have had to do a minor/whitespace commit to trigger the website update, e.g.:
https://github.com/apache/incubator-madlib-site/commit/c77eb2279c6c6dac55d1766d6f1ac4cc3eef3160

**Comment by fmcquillan99** [comment]
design.pdf only displays the top 150 pages in the github viewer, can you please confirm the whole document is there?

**Comment by edespino** [comment]
@fmcquillan99 = This PR does include updates to download.html. I have validated the new links.

**Comment by fmcquillan99** [comment]
great thanks.

LGTM +1

**Pull request merged**
